// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNjAiQNcQTHBVUO38JZ3S4CML8Mt4rtys',
    appId: '1:164293553674:web:c517c5b14edf7e590e39f3',
    messagingSenderId: '164293553674',
    projectId: 'mobiusdatabase',
    authDomain: 'mobiusdatabase.firebaseapp.com',
    storageBucket: 'mobiusdatabase.firebasestorage.app',
    measurementId: 'G-JR5BCHZ3X7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACRVXWY-mb9TfodlKFL7rCOXj990wMbI0',
    appId: '1:164293553674:android:cc2e6d258f7e035d0e39f3',
    messagingSenderId: '164293553674',
    projectId: 'mobiusdatabase',
    storageBucket: 'mobiusdatabase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6gay7gXbgebLTCscGRxKOdWgu2Lu27Fg',
    appId: '1:164293553674:ios:e8b0d5082619c3ff0e39f3',
    messagingSenderId: '164293553674',
    projectId: 'mobiusdatabase',
    storageBucket: 'mobiusdatabase.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6gay7gXbgebLTCscGRxKOdWgu2Lu27Fg',
    appId: '1:164293553674:ios:e8b0d5082619c3ff0e39f3',
    messagingSenderId: '164293553674',
    projectId: 'mobiusdatabase',
    storageBucket: 'mobiusdatabase.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNjAiQNcQTHBVUO38JZ3S4CML8Mt4rtys',
    appId: '1:164293553674:web:e614f386a063db1d0e39f3',
    messagingSenderId: '164293553674',
    projectId: 'mobiusdatabase',
    authDomain: 'mobiusdatabase.firebaseapp.com',
    storageBucket: 'mobiusdatabase.firebasestorage.app',
    measurementId: 'G-34QF3X7FJ9',
  );

}