// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdAdJjY86j57dg9Yq32qZGtnJfIMGMWoE',
    appId: '1:830030728492:web:ed7d9f9cff317f8655b089',
    messagingSenderId: '830030728492',
    projectId: 'mobius-38958',
    authDomain: 'mobius-38958.firebaseapp.com',
    storageBucket: 'mobius-38958.firebasestorage.app',
    measurementId: 'G-QS9BQP13H0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ4C197QKyei6UcXS317IQzmQmoTkIiXE',
    appId: '1:830030728492:android:cc52fc88700a34c955b089',
    messagingSenderId: '830030728492',
    projectId: 'mobius-38958',
    storageBucket: 'mobius-38958.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCThVXof5lS86jPANxO1NI71XspINJzHRw',
    appId: '1:830030728492:ios:5f133cdaae8a013b55b089',
    messagingSenderId: '830030728492',
    projectId: 'mobius-38958',
    storageBucket: 'mobius-38958.firebasestorage.app',
    iosBundleId: 'com.abhinav.mobius',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCThVXof5lS86jPANxO1NI71XspINJzHRw',
    appId: '1:830030728492:ios:41e07d22325eb8a655b089',
    messagingSenderId: '830030728492',
    projectId: 'mobius-38958',
    storageBucket: 'mobius-38958.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdAdJjY86j57dg9Yq32qZGtnJfIMGMWoE',
    appId: '1:830030728492:web:687e8f2b2595de3555b089',
    messagingSenderId: '830030728492',
    projectId: 'mobius-38958',
    authDomain: 'mobius-38958.firebaseapp.com',
    storageBucket: 'mobius-38958.firebasestorage.app',
    measurementId: 'G-DHLMS7D70Q',
  );

}